- name: Setup Dockerized React + Node.js App
  hosts: web
  become: true
  vars:
    app_path: /home/azureuser/gps

  tasks:
    - name: Ensure Docker is available
      command: docker --version
      register: docker_version
      ignore_errors: true

    - name: Fail if Docker is not installed
      fail:
        msg: "Docker is not installed on the VM. Please install it before running this playbook."
      when: docker_version.rc != 0

    - name: Ensure Docker Compose is available
      command: docker-compose --version
      register: compose_version
      ignore_errors: true

    - name: Fail if Docker Compose is not installed
      fail:
        msg: "Docker Compose is not installed on the VM. Please install it before running this playbook."
      when: compose_version.rc != 0

    - name: Add azureuser to docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Clone the GitHub Repo
      git:
        repo: https://github.com/JNilukshan/GPS.git
        dest: "{{ app_path }}"
        version: main
        force: yes

    - name: Create backend .env from variables
      copy:
        dest: "{{ app_path }}/backend/.env"
        content: |
          MONGO_URI={{ lookup('env', 'MONGO_URI') }}
          JWT_SECRET={{ lookup('env', 'JWT_SECRET') }}
          SUPABASE_URL={{ lookup('env', 'SUPABASE_URL') }}
          SUPABASE_KEY={{ lookup('env', 'SUPABASE_KEY') }}
          PORT=5000
          EMAIL_USER={{ lookup('env', 'EMAIL_USER') }}
          EMAIL_PASS={{ lookup('env', 'EMAIL_PASS') }}

    - name: Create frontend .env from variables
      copy:
        dest: "{{ app_path }}/frontend/.env"
        content: |
          VITE_API_URL={{ lookup('env', 'VITE_API_URL') }}

    - name: Start Docker containers (disable BuildKit)
      shell: |
        export DOCKER_BUILDKIT=0
        docker-compose up -d --build
      args:
        chdir: "{{ app_path }}"
